#!/bin/bash

while read oldrev newrev ref
do
  branch=`echo $ref | cut -d/ -f3`

  if [ "master" == "${branch}" ] || [ "beta" == "${branch}" ]; then
    siteroot="/home/shiftcodestk"
    deployments="${siteroot}/deployments"
    repository="${siteroot}/repository"
    
    # Set Branch-specific variables
    if [ "master" == "${branch}" ]; then
      branchDeploymentPath="${deployments}/stable"
      branchPublicPath="$branchDeploymentPath/public"
    else
      branchDeploymentPath="${deployments}/beta"
      branchPublicPath="${branchDeploymentPath}/src/public"
    fi

    # Update Repository Permissions
    chmod -R 0700 "${repository}"

    # Deploy the repository
    git --work-tree="${branchDeploymentPath}" checkout -f "${branch}"
    # Copy Repository Information
    cp -r .git "{$branchDeploymentPath}"

    # Generate project files
    cd "${branchDeploymentPath}"
    nvs use auto
    npm install
    composer install
    gulp build

    # Update deployed file permissions
    cd "${branchDeploymentPath}"
    find . \
      -path "./node_modules*" -prune -o \
      -path "./vendor*" -prune -o \
      -type d \
      -exec chmod 0711 {} \;
    find . \
      -path "./node_modules*" -prune -o \
      -path "./vendor*" -prune -o \
      -type f \
      -exec chmod 0700 {} \; 

    cd "${branchPublicPath}"
    find . \
      -type d \
      -exec chmod -R 0755 {} \;
    find . \
      -type f \
      -exec chmod -R 0744 {} \;

    chmod 0700 "${branchDeploymentPath}/node_modules"
    chmod 0700 "${branchDeploymentPath}/vendor"
    chmod 0700 "${branchPublicPath}/initialize.php"
  fi;
done