#!/bin/bash

while read oldrev newrev ref
do
  branch=`echo $ref | cut -d/ -f3`

  if [ "master" == "${branch}" ] || [ "beta" == "${branch}" ]; then
    siteroot="/home/shiftcodestk"
    deployments="${siteroot}/deployments"
    repository="${siteroot}/repository"
    
    # Set Branch-specific variables
    if [ "master" == "${branch}" ]; then
      branchDeploymentPath="${deployments}/stable"
      branchPublicPath=$branchDeploymentPath
    else
      branchDeploymentPath="${deployments}/beta"
      branchPublicPath="${branchDeploymentPath}/src/public"
    fi

    # Update Repository Permissions
    chmod -R 0700 $repository

    # Deploy the repository
    git --work-tree=$branchDeploymentPath checkout -f $branch
    cd $branchDeploymentPath

    # Generate project files
    nvs use auto
    npm install
    composer install
    gulp build

    # Update deployed file permissions
    find $branchDeploymentPath --type d --exec chmod -R 0711
    find $branchDeploymentPath \( -path "${branchDeploymentPath}/node_modules" -prune -o -path "${branchDeploymentPath}/vendors" -prune -o \) --type f --exec chmod -R 0700
    find $branchPublicPath --type d --exec chmod -R 0755
    find $branchPublicPath --type f --exec chmod -R 0744
    chmod 0700 "${branchPublicPath}/initialize.php"
  fi;
done