<?php
  $page['meta'] = [
    'title'       => 'How to Redeem: GOTY - ShiftCodesTK',
    'description' => 'How to redeem SHiFT Codes in Borderlands: Game of the Year Edition',
    'canonical'   => '/help/how-to-redeem/bl1',
    'image'       => 'bl1/2',
    'theme'       => 'bl1'
  ];

  require_once('../../initialize.php');
?><!doctypehtml><html lang=en><meta charset=utf-8><?php include_once('global/sharedStyles.php'); ?><link href="/assets/css/local/help/how-to-redeem/instructions.css<?= TK_VERSION_STR; ?>"rel=stylesheet><?php include_once('global/head.php'); ?><body data-theme=bl1><?php include_once('global/beforeContent.php'); ?><?php include_once('global/main-header.php'); ?><main class=content-wrapper><?php include_once('local/how-to-redeem-instructions.php'); ?></main><div class=setup><div class="step 1">Navigate to the Main Menu. Then, select <em>Extras</em>.</div><div class="step 2">Select <em>SHiFT</em>.</div><div class="step 3">If you have not already registered and signed in to <strong>SHiFT</strong>, you will be prompted to do so.</div><div class="step 4">If you are not automatically redirected, press the indicated key to reach the <strong>SHiFT Code</strong> page.</div><div class="step 5">Enter the 25-character SHiFT Code into the provided fields. Once you are finished, click <em>Submit</em>.</div><div class="step 6">If successful, you will receive a confirmation message. The reward from the SHiFT Code will also appear on the <strong>My Rewards</strong> page.</div><div class="step 7">You can now make your way to the <strong>Golden Chest</strong> in <strong>Fyrestone</strong> or <strong>New Haven</strong> to spend your Golden Keys. Both Golden Chests can be found in close proximity to the <strong>Fast Travel Station</strong>. Opening the chest will cost <strong>one Golden Key</strong>, and the rewards will be droppped at the <strong>level of your current character</strong>, regardless of playthrough.</div></div><?php include_once('local/support-footer.php'); ?><?php include_once('global/afterContent.php'); ?><?php include_once('global/sharedScripts.php'); ?><script async src="/assets/js/local/help/how-to-redeem/instructions.js<?= TK_VERSION_STR; ?>"></script>