<?php
  $page['meta'] = [
    'title'       => 'How to Redeem: Online - ShiftCodesTK',
    'description' => 'How to redeem SHiFT Codes on the SHiFT website',
    'canonical'   => '/help/how-to-redeem/shift-website',
    'image'       => 'bl1/4',
    'theme'       => 'main'
  ];

  require_once('../../initialize.php');
?><!doctypehtml><html lang=en><meta charset=utf-8><?php include_once('global/sharedStyles.php'); ?><link href="/assets/css/local/help/how-to-redeem/instructions.css<?= TK_VERSION_STR; ?>"rel=stylesheet><?php include_once('global/head.php'); ?><body data-theme=main><?php include_once('global/beforeContent.php'); ?><?php include_once('global/main-header.php'); ?><main class=content-wrapper><?php include_once('local/how-to-redeem-instructions.php'); ?><div class=note><strong>Note:</strong> While the appearance of the site may differ between devices, the steps should remain the same.</div></main><div class=setup><div class="step 1">Navigate to <a aria-label="Official SHiFT website"class=themed href=https://shift.gearboxsoftware.com title="Official SHiFT website"rel="noopener external"target=_blank><span aria-label="External Link"class="fa-external-link-square-alt fas"title="External Link"> </span>shift.gearboxsoftware.com</a>. If you have not already registered and signed in, you will be prompted to do so.</div><div class="step 2">Once you have reached your home page, select <em>Rewards</em> from the menu.</div><div class="step 3">Enter the 25-character SHiFT Code into the provided field. Once you are finished, click <em>Check</em>.</div><div class="step 4">If the SHiFT Code is available for multiple platforms, you will be prompted to select which platform the SHiFT Code should be redeemed for. You can redeem the SHiFT Code for as many platforms as you would like.</div><div class="step 5">If successful, you will receive a confirmation message. If the SHiFT Code is for <em>Borderlands: The Pre-Sequel</em> or <em>Borderlands 3</em>, additional steps are required to receive your rewards. Refer to the <a aria-label="How to Redeem SHiFT Codes in Borderlands: The Pre-Sequel"class=themed href=tps#step_8 title="How to Redeem SHiFT Codes in Borderlands: The Pre-Sequel">Borderlands: The Pre-Sequel</a> and <a aria-label="How to Redeem SHiFT Codes in Borderlands 3"class=themed href=bl3#step_6 title="How to Redeem SHiFT Codes in Borderlands 3">Borderlands 3</a> instructions respectively for more information.</div></div><?php include_once('local/support-footer.php'); ?><?php include_once('global/afterContent.php'); ?><?php include_once('global/sharedScripts.php'); ?><script async src="/assets/js/local/help/how-to-redeem/instructions.js<?= TK_VERSION_STR; ?>"></script>