<?php
  $page['meta'] = [
    'title'       => 'How to Redeem SHiFT Codes - ShiftCodesTK',
    'description' => 'How to redeem SHiFT Codes in Borderlands',
    'canonical'   => '/help/how-to-redeem',
    'image'       => 'bl3/4',
    'theme'       => 'main'
  ];

  require_once('../../initialize.php');
?><!doctypehtml><html lang=en><meta charset=utf-8><?php include_once('global/sharedStyles.php'); ?><link href="/assets/css/local/help/how-to-redeem/index.css<?= TK_VERSION_STR; ?>"rel=stylesheet><?php include_once('global/head.php'); ?><body data-theme=main><?php include_once('global/beforeContent.php'); ?><?php include_once('global/main-header.php'); ?><main class=content-wrapper><p class=intro>Unsure of what to do with the SHiFT Codes once you've found them? No problem! Choose one of the guides below for step-by-step instructions on redeeming SHiFT Codes and getting at that sweet loot!<div class=links><div class=title>Redeem In-Game</div><a aria-label="How to Redeem SHiFT Codes in Borderlands 3"class="button color-light"href=bl3 title="How to Redeem SHiFT Codes in Borderlands 3">Borderlands 3</a><a aria-label="How to Redeem SHiFT Codes in Borderlands: Game of the Year Edition"class="button color-light"href=bl1 title="How to Redeem SHiFT Codes in Borderlands: Game of the Year Edition">Borderlands: GOTY</a><a aria-label="How to Redeem SHiFT Codes in Borderlands 2"class="button color-light"href=bl2 title="How to Redeem SHiFT Codes in Borderlands 2">Borderlands 2</a><a aria-label="How to Redeem SHiFT Codes in Borderlands: The Pre-Sequel"class="button color-light"href=tps title="How to Redeem SHiFT Codes in Borderlands: The Pre-Sequel">Borderlands: TPS</a></div><div class=links><div class=title>Redeem Online</div><a aria-label="How to Redeem SHiFT Codes on the Borderlands website"class="button color-light"href=borderlands-website title="How to Redeem SHiFT Codes on the Borderlands website">Borderlands Website</a><a aria-label="How to Redeem SHiFT Codes on the SHiFT website"class="button color-light"href=shift-website title="How to Redeem SHiFT Codes on the SHiFT website">SHiFT Website</a></div></main><?php include_once('local/support-footer.php'); ?><?php include_once('global/afterContent.php'); ?><?php include_once('global/sharedScripts.php'); ?>