<?php
  namespace ShiftCodesTK\Database;

  /** Properties & Methods used for connecting to and querying the ShiftCodesTK Database */
  trait MysqliMixin {
    /**
     * @var mysqli|null|false The ShiftCodesTK Database Connection Handle. Represents the connection between PHP and the ShiftCodesTK Database.
     * - Has a value of **null** if the database connection has not yet been initialized.
     * - Has a value of **false** if an error occurred while connecting to the Database. 
     */
    private $mysqli = null;

    /**
     * Check for errors generated by a `mysqli` function.
     * 
     * @param bool $check_connection Indicates if the function should check for *connection errors* instead of *function call errors*.
     * @param callable $callback A function to be invoked if an error has occured.
     * @return true Returns **true** if no errors were generated by the last `mysqli` function call.
     * @throws Error Throws an error if the last `mysqli` function call generated an error.
     */
    public function check_mysqli_errors (bool $check_connection = false, callable $callback = null) {
      $errno = $check_connection
               ? 'connect_errno'
               : 'errno';

      if ($this->mysqli->$errno) {
        if ($callback) {
          $callback($this->mysqli);
        }
        
        throw new \Error($this->mysqli->error);
      }

      return true;
    }
  }
?>