<?php
  $page['meta'] = [
    'title'       => 'Updates - ShiftCodesTK',
    'description' => 'Recent changes and updates to ShiftCodesTK',
    'canonical'   => '/updates',
    'image'       => 'bl2/5',
    'theme'       => 'main'
  ];

  require_once('initialize.php');
?><!doctypehtml><html lang=en><meta charset=utf-8><?php include_once('global/sharedStyles.php'); ?><link href="/assets/css/local/updates.css<?php echo TK_VERSION_STR; ?>"rel=stylesheet><?php include_once('global/head.php'); ?><body data-theme=main><?php include_once('global/beforeContent.php'); ?><?php include_once('global/main-header.php'); ?><header class=updates-header id=updates_header><div class=content-wrapper><div class="section current"><span><span class=title>Current Version:</span> <strong class=currentver><?php echo $serverVersion; ?></strong></span></div><div class="section jump"><button aria-disabled=true aria-haspopup=true aria-label="Jump to Changelog"aria-pressed=false autocomplete=off data-pressed=false disabled id=updates_header_jump title="Jump to Changelog"><span>Jump to <span class="fas fa-caret-down"></span></span></button><div class="no-auto-config dropdown-menu no-refocus o-toggle"id=updates_header_jump_dropdown data-align=right data-pos=bottom data-target=updates_header_jump><div class=panel><div class=title>Jump to:</div><ul class="choice-list scrollable"></ul></div></div></div></div></header><main class=content-wrapper><div class=full-changelog-link>This is a simplified list of changes related to ShiftCodesTK's service. For the complete list of changes, visit the <strong>Releases</strong> page on <a aria-label="ShiftCodesTK Releases on Github"class=themed href=https://github.com/FusedKush/ShiftCodesTK/releases title="ShiftCodesTK Releases on Github"rel="external noopener"target=_blank><span class="fas fa-external-link-square-alt"aria-label="External Link"title="External Link"> </span>GitHub</a></div><div id=changelog_list></div><div class="no-auto-config pager"id=changelog_pager data-offset=10 data-onclick=updates_header_jump data-subtractoffset=true></div><div class=overlay id=changelog_overlay><?php include_once('local/spinner.php'); ?></div></main><template id=changelog_template><section class="changelog dropdown-panel"><button class="dropdown-panel-toggle header"data-custom-labels='{"false": "Expand Changelog", "true": "Collapse Changelog"}'><div class=wrapper><div class=title><div class=icon><span class=fas></span></div><div class=string><h2 class="primary version"></h2><div class="info secondary"><span class=date></span><span class=separator>•</span><span class=type></span></div></div></div><div class=indicator><span class="fas fa-chevron-right"></span></div></div></button><div class="body content-container"></div></section></template><template id=changelog_jump_template><li role=menuitem><a aria-label="Jump to Version 1.0.0 Changelog"class=choice href=# title="Jump to Version 1.0.0 Changelog"><span></span></a></template><?php include_once('global/afterContent.php'); ?><?php include_once('global/sharedScripts.php'); ?><script async src="/assets/js/local/updates.js<?php echo TK_VERSION_STR; ?>"></script>